### PR TITLE
Added Purple Monkey Game Jam.

### PR DESCRIPTION
**Pull request by neogeek**

### CODE REVIEW

**Comment by 0x0961h** [comment]
Merged, thanks!

**Comment by neogeek** [comment]
Has this PR been published on the main site yet? I've checked my local build and it looks ok. Just wanted to make sure I didn't mess anything up in the JSON file.

**Comment by 0x0961h** [comment]
Hm... I'll poke leafo now.

**Comment by 0x0961h** [comment]
Deployed, check the site (it may require you to press Ctrl-F5 to force reload)

**Comment by neogeek** [comment]
Cool, thanks for your help!

**Pull request merged**
