### PR TITLE
Added 2015 Adventure Jam

### PR DESCRIPTION
**Pull request by chongdashu**
Adding 2015 Adventure Jam.

### CODE REVIEW

**Comment by 0x0961h** [comment]
Merged, thanks!

**Comment by chongdashu** [comment]
Thanks :)

**Comment by chongdashu** [comment]
Just a quick check -- is there something else I need to do for the jam to appear on the site? Thanks!

**Comment by leafo** [comment]
Nope, just need to manually refresh the page. It's there now.

**Comment by chongdashu** [comment]
Yay! Thanks :-) Just wanted to make sure I didn't make a mistake! Thanks so much!

**Pull request merged**
