### PR TITLE
Update 2015.json

### PR DESCRIPTION
**Pull request by riotjayne**
Added #JamForLeelah

### CODE REVIEW

**Comment by 0x0961h** [comment]
Lines 8 and 9 should end with comma (,).

**Comment by 0x0961h** [comment]
Oh, and... remove the comma on the line 10. After that, I think, everything will be fine.

**Comment by riotjayne** [comment]
Thank you, I think it should work now

**Comment by 0x0961h** [comment]
Eeyup, everything's fine.

**Pull request merged**
