### PR TITLE
Add teacart1K

### PR DESCRIPTION
**Pull request by jackaperkins**
yay! :heart:

### CODE REVIEW

**Comment by leafo** [comment]
WAHHOOO

**Comment by jackaperkins** [comment]
:) :)

**Comment by jackaperkins** [comment]
Wait, just now realized you run do both itch and compohub! Are you ever gonna merge the autogened ones from the itch comps into the main compohub?

**Comment by leafo** [comment]
probably at some point, working on compohub is low priority for me at the moment.

**Pull request merged**
