### PR TITLE
add GMC Jam 17

### PR DESCRIPTION
**Pull request by jimmymb**
Could you please add Gamemaker Community Jam #17 to compohub? Cheers :)

### CODE REVIEW

**Comment by 0x0961h** [comment]
Merged, thanks!

**Comment by jimmymb** [comment]
Cheers, I just checked the site and it's not coming up? Perhaps it has somethings to do with me adding it to the "2014.json" instead of the "2015.json"...

**Comment by 0x0961h** [comment]
Well, it won't coming up until @leafo upload a new build to CompoHub manually, so we just need to poke him.

Aaaand I don't think it's too critical that you've added it to 2014.json. Though, it's not very... correct. If you wish, I can revert your commit and you'll make another pull request with a new jam in 2015.json.

**Comment by jimmymb** [comment]
Haha, that would be good
I'll make the new pull now, cheers :)

**Pull request merged**
